name: Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java (for Gradle)
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: gradle

    - name: Build project
      run: |
        chmod +x ./gradlew
        # Inject package name into build files
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        
        # Run Gradle build
        ./gradlew :module:assembleRelease

    - name: Zip output
      run: |
        mkdir -p build_artifacts
        zip -r "build_artifacts/zygisk-il2cppdumper-${{ github.event.inputs.package_name }}.zip" out/magisk_module_release/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
        path: build_artifacts/zygisk-il2cppdumper-${{ github.event.inputs.package_name }}.zip
